---

- name: Create groups playbook
  hosts: ubuntu
  become: true
  tasks:
  - name: Create groups
    group:
      name: "{{ item }}"
      state: present
    loop: 
    # Type group name you want to add
    - devops
    - cloud
    - infra
